version: '3.7'

services:
  webrtc-streaming-sfu:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
        - ./src:/home/node/app/src
        - ./nodemon.json:/home/node/app/nodemon.json

    container_name: webrtc-streaming-sfu
    expose:
      - "8888"
      - "2000-3000"
    ports:
      - "8888:8888"
      - "2000-3000:2000-3000"
    command: npm run dev