export const MOCK_STREAMS = {
  HAMSTER: { id: "hamster", title: "Hamster's on a call", viewersCount: "69k" },
};

export const USERNAME_OPTIONS = [
  "Cosmic Voyager",
  "Starry Pioneer",
  "Nebula Navigator",
  "Galactic Guru",
  "Astro Adept",
  "Celestial Seeker",
  "Void Vagabond",
  "Planet Pilgrim",
  "Solar Sailor",
  "Quasar Quester",
  "Meteor Marauder",
  "Eclipse Explorer",
  "Comet Chaser",
  "Orbital Outlaw",
  "Starlight Strider",
  "Moon Mystic",
  "Interstellar Inventor",
  "Black Hole Bandit",
  "Supernova Surfer",
  "Cosmos Commander",
  "Aurora Adventurer",
  "Galaxy Guardian",
  "Lunar Legend",
  "Satellite Scout",
  "Dimensional Drifter",
  "Stellar Scholar",
  "Void Voyager",
  "Exoplanet Explorer",
  "SpaceTime Sailor",
  "Orion Observer",
  "Photon Pioneer",
  "Gravity Guru",
  "Milky Way Maverick",
  "Astrology Analyst",
  "Nebula Nomad",
  "Cosmic Curator",
  "Star Cluster Strategist",
  "Quantum Quester",
  "Universe Unveiler",
  "Galactic Geologist",
  "Meteorite Miner",
  "Solar Storm Seeker",
  "DarkMatter Detective",
  "Cosmic Collector",
  "Space Spectator",
  "Event Horizon Enthusiast",
  "Lightyear Learner",
  "Rocket Rider",
  "Astrophysics Aficionado",
  "Planet Pathfinder",
];
